#!/bin/bash
WORKING_DIR=$(pwd)
if [ "$1" == "search" ] ; then
    rm -r search-EXP-*
    echo "Starting Search"
    python ./cnn/train_search.py --unrolled --batch_size=4 --report_freq=1 ${*:2}
elif [ "$1" == "train" ] ; then
    echo "Starting Training the full model"
    python ./cnn/train.py --report_freq 1 ${*:2}
elif [ "$1" == "predict" ] ; then
    echo "Starting Predictions"
    python ./cnn/predict.py ${*:2}
elif [ "$1" == "visualize" ] ; then
    echo "Making cell structures"
    python ./cnn/visualize.py ${*:2}
    echo "Navigate to $WORKING_DIR/cnn/final_model/cells"
else
    echo "No command $1 found! Use search / train / predict / visualize"
fi